# Screen constants
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 500
SCREEN_TITLE = "Crazy Lab.py"

# Character constants
MOVEMENT_SPEED = 5
SPRITE_SCALING = 0.8

#Enemies
ENEMY_SCALING = 0.5
LIMIT_TOP = 600
LIMIT_BOTTOM = 0
SECONDS_TO_SPAWN = 6
ENEMY_SPEED = 1

# Physics
GRAVITY = 1
PLAYER_JUMP_SPEED = 22
PLAYER_MOVEMENT_SPEED = 5

# Background constants
BACKGROUND_SCALE = 2.5

#Sound Constants
MUSIC_VOLUME = 0.1
JUMP_VOLUME = 0.3
REWARD_VOLUME = 0.2
NEW_LEVEL_VOLUME = 0.4
NEW_LEVEL_MUSIC_VOLUME = 0.15

#Platforms constants
PLATFORM_SPEED = 1
BLOCK_SIZE = 0.2

#Rewards constants
NUMBER_OF_REWARDS = 5
REWARD_SIZE = 0.15


#BOSS
BOSS_SIZE: 1
# Custom Colours
GREY = (106, 106, 86)